def evaluate_scraping_quality(
    url, raw_html, article_details, min_text_len=200, min_ratio=0.05
):
    """
    Enhanced scraping quality evaluation with bot detection, error page detection, and content validation.

    If a valid summary was generated by Gemini, we trust it as a strong quality signal.

    Returns a dict containing quality metrics and a flag indicating whether the content is usable.
    """
    raw_html_length = len(raw_html) if raw_html else 0
    text = article_details.get("text", "") if article_details else ""
    text_length = len(text)

    # Error messages that indicate scraping failed
    ERROR_INDICATORS = [
        "javascript",
        "cookies",
        "browser not supporting",
        "please enable",
        "access denied",
        "403 forbidden",
        "404 not found",
        "500 internal server error",
        "503 service unavailable",
        "captcha",
        "verify you are human",
        "cloudflare",
        "bot detection",
        "unusual traffic",
        "reference id",
        "error loading",
        "could not be loaded",
        "content blocked",
        "permission denied",
        "security check",
        "rate limit",
    ]

    # Check for bot detection / error pages
    text_lower = text.lower()
    error_count = sum(1 for indicator in ERROR_INDICATORS if indicator in text_lower)
    has_error_indicators = error_count >= 2  # Multiple indicators = likely error page

    # Check for very short "articles" that are just error messages
    if text_length < 100 and error_count >= 1:
        has_error_indicators = True

    # Check if text is just gibberish or random characters
    if text_length > 0:
        # Count alphabetic characters vs total
        alpha_count = sum(1 for c in text if c.isalpha())
        alpha_ratio = alpha_count / text_length
        is_gibberish = alpha_ratio < 0.5  # Less than 50% letters = gibberish
    else:
        is_gibberish = True

    # Check if summary exists and isn't an error
    summary = article_details.get("summary", "")
    summary_length = len(summary)
    has_valid_summary = (
        summary_length >= 50 and
        not any(indicator in summary.lower() for indicator in ["error", "could not be loaded", "javascript", "cookies"])
    )

    # Calculate HTML-to-text ratio
    html_to_text_ratio = (
        round(text_length / raw_html_length, 4) if raw_html_length else 0
    )

    # Enhanced quality check with summary-based leniency
    # If we have a valid summary from Gemini, trust it even if HTML ratio is low
    # (Gemini won't generate good summaries from garbage content)
    summary_based_pass = (
        has_valid_summary and
        text_length >= min_text_len and
        not has_error_indicators and
        not is_gibberish
    )

    strict_pass = (
        text_length >= min_text_len and
        html_to_text_ratio >= min_ratio and
        not has_error_indicators and
        not is_gibberish and
        has_valid_summary
    )

    # Pass if either strict checks pass OR summary-based check passes
    is_clean = strict_pass or summary_based_pass

    return {
        "url": url,
        "raw_html_length": raw_html_length,
        "text_length": text_length,
        "summary_length": summary_length,
        "html_to_text_ratio": html_to_text_ratio,
        "error_indicators_found": error_count,
        "has_error_indicators": has_error_indicators,
        "is_gibberish": is_gibberish,
        "has_valid_summary": has_valid_summary,
        "is_clean": is_clean,
        "passed_via_summary": summary_based_pass and not strict_pass,
        "rejection_reason": _get_rejection_reason(
            text_length, min_text_len, html_to_text_ratio, min_ratio,
            has_error_indicators, is_gibberish, has_valid_summary, summary_based_pass
        )
    }


def _get_rejection_reason(text_len, min_text_len, ratio, min_ratio,
                          has_errors, is_gibberish, has_summary, summary_pass):
    """Helper to identify why an article was rejected"""
    if text_len < min_text_len:
        return f"Text too short ({text_len} < {min_text_len})"
    if has_errors:
        return "Error page/bot detection detected"
    if is_gibberish:
        return "Gibberish/non-text content"
    if not has_summary:
        return "Invalid or missing summary"
    if ratio < min_ratio and not summary_pass:
        return f"Low HTML ratio ({ratio} < {min_ratio}) and no valid summary"
    if summary_pass:
        return "Passed via valid Gemini summary (HTML ratio waived)"
    return "Passed all strict checks"
