apiVersion: v1
kind: ConfigMap
metadata:
  name: sentifinance-config
data:
  # Non-sensitive configuration
  FLASK_ENV: "production"
  APP_DEBUG: "False"
  LOG_LEVEL: "INFO"
  PORT: "5001"
  MAIL_SERVER: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_USE_TLS: "True"
  MAIL_USE_SSL: "False"
---