"""update active learning new columns

Revision ID: 2fa84f267147
Revises: 2c6b630a093f
Create Date: 2025-11-07 23:53:44.680027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa84f267147'
down_revision = '2c6b630a093f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labeling_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_weights', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('integration_reason', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('finbert_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('llm_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('both_confident', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_financial_heavy', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('final_combined_score', sa.Float(), nullable=True))
        batch_op.alter_column('news_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_labeling_queue_news_id'), ['news_id'], unique=False)

    with op.batch_alter_table('user_votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_votes_news_id'), ['news_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_votes_news_id'))
        batch_op.drop_column('news_id')

    with op.batch_alter_table('labeling_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labeling_queue_news_id'))
        batch_op.alter_column('news_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('final_combined_score')
        batch_op.drop_column('is_financial_heavy')
        batch_op.drop_column('both_confident')
        batch_op.drop_column('llm_confidence')
        batch_op.drop_column('finbert_confidence')
        batch_op.drop_column('integration_reason')
        batch_op.drop_column('model_weights')

    # ### end Alembic commands ###
