"""Initial migration

Revision ID: 78880d12afa3
Revises: 
Create Date: 2025-08-28 18:34:07.927696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78880d12afa3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('finbert_score', sa.Float(), nullable=True),
    sa.Column('gemini_score', sa.Float(), nullable=True),
    sa.Column('open_ai_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('time_decay', sa.Float(), nullable=True),
    sa.Column('simple_average', sa.Float(), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('news',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('publisher', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('entities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('finbert_score', sa.Float(), nullable=True),
    sa.Column('second_model_score', sa.Float(), nullable=True),
    sa.Column('third_model_score', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('agreement_rate', sa.Float(), nullable=True),
    sa.Column('company_names', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('regions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('sectors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('CLIENT', 'RELATIONSHIP_MANAGER', name='userrole'), nullable=False),
    sa.Column('rm_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rm_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('userID', sa.UUID(), nullable=False),
    sa.Column('assessment', sa.String(length=50), nullable=False),
    sa.Column('newsID', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['newsID'], ['news.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentiment_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentiment_history')
    op.drop_table('feedback')
    op.drop_table('user')
    op.drop_table('news')
    op.drop_table('entity')
    # ### end Alembic commands ###
