"""Add client_preferences table with updated field types

Revision ID: ac720183eb7d
Revises: 32e7eb06cc0d
Create Date: 2025-09-15 16:23:31.018032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac720183eb7d'
down_revision = '32e7eb06cc0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('holding', sa.Float(), nullable=True),
    sa.Column('overall_pl', sa.Float(), nullable=True),
    sa.Column('stop_loss_tolerance', sa.Float(), nullable=True),
    sa.Column('risk_cap', sa.String(), nullable=True),
    sa.Column('sectors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_preferences')
    # ### end Alembic commands ###
