"""add active learning tables

Revision ID: e517a70ef520
Revises: d135f99bd24b
Create Date: 2025-10-31 05:53:39.955164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e517a70ef520'
down_revision = 'd135f99bd24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labeling_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.String(length=50), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('finbert_score', sa.Float(), nullable=False),
    sa.Column('llm_score', sa.Float(), nullable=False),
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('disagreement_score', sa.Float(), nullable=False),
    sa.Column('uncertainty_score', sa.Float(), nullable=False),
    sa.Column('sampling_reason', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', name='queuestatus'), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=True),
    sa.Column('feature_names_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('labeling_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labeling_queue_id'), ['id'], unique=False)

    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('training_samples', sa.Integer(), nullable=False),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_runs_id'), ['id'], unique=False)

    op.create_table('aggregated_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_item_id', sa.Integer(), nullable=False),
    sa.Column('final_label', sa.Enum('BULLISH', 'BEARISH', 'NEUTRAL', name='finalsentiment'), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('agreement_rate', sa.Float(), nullable=False),
    sa.Column('aggregation_method', sa.String(length=50), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['queue_item_id'], ['labeling_queue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queue_item_id')
    )
    with op.batch_alter_table('aggregated_labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aggregated_labels_id'), ['id'], unique=False)

    op.create_table('user_stats',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_votes', sa.Integer(), nullable=False),
    sa.Column('gold_standard_correct', sa.Integer(), nullable=False),
    sa.Column('gold_standard_total', sa.Integer(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('last_active', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vote', sa.Enum('BULLISH', 'BEARISH', 'NEUTRAL', name='sentimentvote'), nullable=False),
    sa.Column('vote_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('session_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['queue_item_id'], ['labeling_queue.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_votes_id'), ['id'], unique=False)

    op.drop_table('feedback')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('userID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('newsID', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['newsID'], ['news.id'], name=op.f('feedback_newsID_fkey')),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], name=op.f('feedback_userID_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_pkey'))
    )
    with op.batch_alter_table('user_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_votes_id'))

    op.drop_table('user_votes')
    op.drop_table('user_stats')
    with op.batch_alter_table('aggregated_labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aggregated_labels_id'))

    op.drop_table('aggregated_labels')
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_runs_id'))

    op.drop_table('model_runs')
    with op.batch_alter_table('labeling_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labeling_queue_id'))

    op.drop_table('labeling_queue')
    # ### end Alembic commands ###
