"""add content and scraped_at to news

Revision ID: e9a8c7d5f341
Revises: d135f99bd24b
Create Date: 2025-11-01 02:19:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a8c7d5f341'
down_revision = 'd135f99bd24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('scraped_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('publisher',
                   existing_type=sa.VARCHAR(length=100),
                   nullable=True)
        batch_op.alter_column('description',
                   existing_type=sa.TEXT(),
                   nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('description',
                   existing_type=sa.TEXT(),
                   nullable=False)
        batch_op.alter_column('publisher',
                   existing_type=sa.VARCHAR(length=100),
                   nullable=False)
        batch_op.drop_column('scraped_at')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
