"""add_client_portfolio_performance_and_preferences_tables

Revision ID: f161aa89fb93
Revises: ac720183eb7d
Create Date: 2025-10-02 23:09:42.092762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f161aa89fb93'
down_revision = 'ac720183eb7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_performance',
    sa.Column('client_uuid', sa.UUID(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('daily_performance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['client_uuid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('client_uuid', 'datetime')
    )
    op.create_table('client_portfolio',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('average_cost_basis', sa.Float(), nullable=True),
    sa.Column('total_invested', sa.Float(), nullable=True),
    sa.Column('first_purchase_date', sa.DateTime(), nullable=True),
    sa.Column('last_transaction_date', sa.DateTime(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('current_market_value', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl_percent', sa.Float(), nullable=True),
    sa.Column('portfolio_allocation_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'entity_id')
    )
    op.create_table('transactions',
    sa.Column('txn_uuid', sa.UUID(), nullable=False),
    sa.Column('client_uuid', sa.UUID(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'DIVIDEND', 'BUY', 'SELL', name='transactiontype'), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'SGD', 'EUR', 'GBP', 'JPY', name='currency'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price_per_share', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['client_uuid'], ['user.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('txn_uuid')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_client_uuid'), ['client_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_datetime'), ['datetime'], unique=False)

    with op.batch_alter_table('client_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_single_position_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_sector_allocation_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('min_cash_reserve_percent', sa.Float(), nullable=True))

    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sector', postgresql.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_column('sector')
        batch_op.drop_column('asset_type')

    with op.batch_alter_table('client_preferences', schema=None) as batch_op:
        batch_op.drop_column('min_cash_reserve_percent')
        batch_op.drop_column('max_sector_allocation_percent')
        batch_op.drop_column('max_single_position_percent')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_datetime'))
        batch_op.drop_index(batch_op.f('ix_transactions_client_uuid'))

    op.drop_table('transactions')
    op.drop_table('client_portfolio')
    op.drop_table('client_performance')
    # ### end Alembic commands ###
